name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          if [ -f backend/test-requirements.txt ]; then pip install -r backend/test-requirements.txt; fi
          if [ -f backend/test_requierements.txt ]; then pip install -r backend/test_requierements.txt; fi
          # Installer moto explicitement pour s'assurer qu'il est disponible
          pip install moto pytest-flask

      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 backend --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify AWS credentials availability
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID is not set. Please add it to your GitHub secrets."
            exit 1
          fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS_SECRET_ACCESS_KEY is not set. Please add it to your GitHub secrets."
            exit 1
          fi
          echo "AWS credentials are available."

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS CLI configuration
        run: |
          aws sts get-caller-identity || echo "AWS CLI verification failed"

      - name: Check if Elastic Beanstalk application exists
        id: check_app
        run: |
          if aws elasticbeanstalk describe-applications --application-names campaign-manager 2>/dev/null; then
            echo "Application exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Application does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Elastic Beanstalk application if it doesn't exist
        if: steps.check_app.outputs.exists == 'false'
        run: |
          aws elasticbeanstalk create-application --application-name campaign-manager

      - name: Create Elastic Beanstalk environment if needed
        id: check_env
        run: |
          if ! aws elasticbeanstalk describe-environments --environment-names campaign-manager-env --application-name campaign-manager | grep -q "campaign-manager-env"; then
            echo "Creating new environment"
            aws elasticbeanstalk create-environment \
              --application-name campaign-manager \
              --environment-name campaign-manager-env \
              --solution-stack-name "64bit Amazon Linux 2023 v4.0.8 running Python 3.11" \
              --option-settings file://ebconfig.json
          fi

      - name: Prepare deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "*.github*" "node_modules/*" "__pycache__/*" "*.pyc" "*.pyo" "*.pyd" "venv/*" "env/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: campaign-manager
          environment_name: campaign-manager-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
