name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          if [ -f backend/test-requirements.txt ]; then pip install -r backend/test-requirements.txt; fi
          pip install moto pytest-flask flake8

      - name: Lint with flake8
        run: |
          flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 backend --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check if Beanstalk app exists
        id: check_app
        run: |
          if aws elasticbeanstalk describe-applications --application-names campaign-manager 2>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Beanstalk app if missing
        if: steps.check_app.outputs.exists == 'false'
        run: |
          aws elasticbeanstalk create-application --application-name campaign-manager

      - name: Check if environment exists
        id: check_env
        run: |
          if aws elasticbeanstalk describe-environments \
            --application-name campaign-manager \
            --environment-names campaign-manager-env \
            --no-include-deleted | grep -q "campaign-manager-env"; then
            echo "env_exists=true" >> $GITHUB_OUTPUT
          else
            echo "env_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create environment if missing
        if: steps.check_env.outputs.env_exists == 'false'
        run: |
          aws elasticbeanstalk create-environment \
            --application-name campaign-manager \
            --environment-name campaign-manager-env \
            --solution-stack-name "64bit Amazon Linux 2023 v4.5.1 running Python 3.13" \
            --option-settings Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,Value=SingleInstance

      - name: Prepare deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "*.github*" "node_modules/*" "__pycache__/*" "*.pyc" "*.pyo" "*.pyd" "venv/*" "env/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: campaign-manager
          environment_name: campaign-manager-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
